### ISSUE TITLE
Setting expecation failed with error AxiosError: Request failed with status code 400

### ISSUE THREAD

**Issue by tkrisztian95** [znsio/specmatic-node#111]
**Describe the bug**
Using the `await setHttpStubExpectations("some file here...", httpStub.url);` i got this error about setting expectations failed and the Specmatic stub server returns with a `400 Bad request`.

Snippet from actual test code:
```
const HTTP_STUB_HOST = "127.0.0.1";
const HTTP_STUB_PORT = 10002;
const TEST_TIMEOUT_MS = 10 * 60 * 1000; //10 mins CI needs a long timeout

describe("Start Service stubbed by Specmatic for contract tests", () => {
  let httpStub;

  beforeAll(async () => {
    httpStub = await startHttpStub(HTTP_STUB_HOST, HTTP_STUB_PORT);
    await setHttpStubExpectations("./templates.json", httpStub.url);
  }, TEST_TIMEOUT_MS);

```

Debug log:
```
[specmatic] 13-12-2023 14:40:32 info: Stub: Stub server is running on http://127.0.0.1:10002. Ctrl + C to stop.

[specmatic] 13-12-2023 14:40:32 info: Set Expectations: Stub url is http://127.0.0.1:10002

stdout | unknown test
[specmatic] 13-12-2023 14:40:33 debug: Stub: 
--------------------
  Request at 2023-12-13 2:40:33.211
    POST /_specmatic/expectations
    Accept: application/json, text/plain, */*
    Content-Type: application/json
    Referer: http://localhost:3000/
    User-Agent: Mozilla/5.0 (linux) AppleWebKit/537.36 (KHTML, like Gecko) jsdom/16.7.0
    Accept-Language: en
    Origin: http://localhost:3000
    Content-Length: 1932
    Accept-Encoding: gzip, deflate
    Host: 127.0.0.1:10002
    Connection: keep-alive
    
    {
        "http-request": {
            "path": "some api path is here...",
            "method": "GET",
            "headers": {
                "Authorization": "Bearer some token is here..."
            }
        },
        "http-response": {
            "status": 200,
            "body": [
                {
                  // some json object is here...
                }
            ],
            "status-text": "OK"
        }
    }

  Response at 2023-12-13 2:40:33.396
    400 Bad Request
    X-Specmatic-Result: failure
    
    No match was found.



stdout | unknown test
[specmatic] 13-12-2023 14:40:33 error: Set Expectations: Failed with error AxiosError: Request failed with status code 400
[specmatic] 13-12-2023 14:40:33 debug: Stub: Stopping server at http://127.0.0.1:10002
[specmatic] 13-12-2023 14:40:33 debug: Trying to stop stub process gracefully ...
```

**To Reproduce**

**Expected behavior**

Some information about why this cannot set/upload the expectations. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 WSL Ubuntu
 - ENV: Locally and CI pipeline too
 - Version: `"^1.0.3"` (NPM package.json)

**Additional context**

When I start stub by the Specmatic CLI eg `specmatic stub service.yaml` it works with the same json file (canned response) from the `service_data` folder.

**Comment by joelrosario** [comment]
Hi @tkrisztian95 can you share the `specmatic.json` file in your directory? `specmatic.json` needs to contain the path of the specification that you want to stub out, in the `stub` section. Here's [documentation](https://specmatic.in/documentation/specmatic_json.html) on how `specmatic.json` should look.

Hope this helps.

**Comment by joelrosario** [comment]
Hi @tkrisztian95, in addition to the above, can you also share the complete Specmatic stub server log from the moment it starts, so that we can see if there are any errors seen when loading the specification.

**Comment by tkrisztian95** [comment]
Aha, I think the issue is in my `specmatic.json`. I had the `test` section point to the API specification, but it should be in `stub` section instead because this is a consumer side test. After I replaced it, it started working.

**Comment by harikrishnan83** [comment]
@tkrisztian95 Thanks for the update. I am marking this issue as closed. cc @joelrosario
