### ISSUE TITLE
Set http stub expectation from static object

### ISSUE THREAD

**Issue by tkrisztian95** [znsio/specmatic-node#138]
**Is your feature request related to a problem? Please describe.**
The function `setHttpStubExpectations` has a `stubPath` parameter. 

**Describe the solution you'd like**
I would like to setup the mock and define request/response from code, without writing it to a json file.

**Comment by harikrishnan83** [comment]
@tkrisztian95 Thanks. This is indeed a valid DevX improvement you have requested. We will work on this.

**Comment by tkrisztian95** [comment]
Thanks @harikrishnan83! Let me know if you need help.

**Comment by harikrishnan83** [comment]
@tkrisztian95 Thanks for offering to help. We would be happy to accept a Pull Request for this feature from you. The [`setExpectations`](https://github.com/znsio/specmatic-node/blob/1304c1c94eb3867284646f4cdab037927e2df8ae/src/core/index.ts#L153) function is internally just reading the JSON contents of the file and sending it over [HTTP POST request to Specmatic stub server expectations API](https://github.com/znsio/specmatic-node/blob/1304c1c94eb3867284646f4cdab037927e2df8ae/src/core/index.ts#L161). We can create another function (maybe we can call it `setExpectationJson`) that directly passes the JSON that we receive to the [Specmatic expectations API](https://specmatic.in/documentation/service_virtualization_tutorial.html#expectations-http-endpoint) which is used for setting dynamic expectations. Please let me know if you have any questions or other suggestions.

**Comment by tkrisztian95** [comment]
I have some time in spare, looking into it. Thanks!

**Comment by tkrisztian95** [comment]
Thank you @harikrishnan83!
