### ISSUE TITLE
Unable to set environment when running through cli

### ISSUE THREAD

**Issue by rtalwar26** [znsio/specmatic-node#5]
I am running the following command 

```shell
npx specmatic test tests/login.spec --host=localhost --port=3000 --environment=development
```
but am getting an error

```shell
Unknown option: '--environment=development'
```

**Comment by rtalwar26** [comment]
i used `--env` instead of `--environment` and it worked. 

someone needs to correct the documentation on [this page](https://specmatic.in/documentation/authentication.html), it mentions the following line 

```
If you’re running the tests from a terminal, the command is specmatic test --environment=staging specfile.spec
```

**Comment by vikram-rao** [comment]
This is fixed now
